apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: lab4
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: lab4-pw
        - name: MYSQL_DATABASE
          value: lab4
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: lab4
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
