apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: lab4
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:latest
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql:3306
        - name: WORDPRESS_DB_PASSWORD
          value: lab4
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: lab4
spec:
  ports:
  - port: 80
  selector:
    app: wordpress
  type: LoadBalancer
