stages:
- stage: Production
  jobs:
  - deployment: DeployToProduction
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION_ID)'
              appType: 'webAppLinux'
              appName: 'mawalab2dev'
              package: '$(System.ArtifactsDirectory)/drop'
            displayName: 'Deploy to Azure Web App'

  - job: ManualValidation
    displayName: 'Manual Validation'
    pool: server
    steps:
    - task: ManualValidation@0
      inputs:
        instructions: 'Please validate the deployment to production.'
        onTimeout: 'reject'
