name: Deploy Node.js App to Azure Static Web App in the Production Environment

on:
  push:
    branches:
      - release

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 
        uses: actions/setup-node@v2 
        with: 
          node-version: 'lts/*'

      - name: Install dependencies 
        working-directory: ./Lab2/api
        run: npm i
      
      - name: Run tests 
        working-directory: ./Lab2/api
        run: npm test
        
      - name: Remove node_modules
        working-directory: ./Lab2/api
        run: rm -rf node_modules
      
      - name: Install production dependencies 
        working-directory: ./Lab2/api
        run: npm i --omit=dev

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_WATER_08B6A5A03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/Lab2" # App source code path
          api_location: "/Lab2/api" # Api source code path
          output_location: ""          
          skip_app_build: true
          skip_api_build: true